In [12]:
"""
Q1: For which of these matrices (A1, A2) does the jacobi iteration and Gauss-Siedel method converge?
"""
import numpy as np
from scipy.linalg import inv, lu

In [8]:
A1 = [[2,-1,2],[1,2,-2],[2,2,2]]
A2 = [[5,5,0],[-1,5,4],[2,3,8]]

In [24]:
"""
Convergence Tests: Every eigenvalue of M=I-P^-1A must have |eigen(M)| < 1
Jacobi Iteration: P = diagonal part D of A
Gauss-Siedel: P = Lower Triangular part of A
"""
def jacobiConvergence(A):
    m, n = len(A), len(A[0])
    
    #constuct Diagonal and Identity matrix
    D = [[0 for x in range(n)] for y in range(m)]
    I = [[0 for x in range(n)] for y in range(m)]
    for x in range(m):
        D[x][x] = A[x][x]
        I[x][x] = 1
        
    #turn into numpy arrays
    A = np.array(A)
    D = np.array(D)
    I = np.array(I)
    
    M = I - (inv(D).dot(A))
    
    w, v = np.linalg.eig(M)
    
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges")

def guasssiedelConvergence(A):
    m, n = len(A), len(A[0])
    
    #construct L and Identity matrix
    P, L, U = lu(A)
    I = [[0 for x in range(n)] for y in range(m)]
    for x in range(m):
        I[x][x] = 1
        
    M = I - (inv(L).dot(A))
    
    w, v = np.linalg.eig(M)
    
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges")

In [25]:
print("Testing Matrix A1")
print("Jacobi Iteration")
jacobiConvergence(A1)
print("Gauss-Siedel")
guasssiedelConvergence(A1)
print("\n")
print("Testing Matrix A2")
print("Jacobi Iteration")
jacobiConvergence(A2)
print("Gauss-Siedel")
guasssiedelConvergence(A2)

Testing Matrix A1
Jacobi Iteration
Does not converge
Gauss-Siedel
Does not converge


Testing Matrix A2
Jacobi Iteration
Converges
Gauss-Siedel
Does not converge


In [65]:
"""
QII: Consider two different fixed-pt iterations to compute the inverse of a regular matrix A(nxn)
     starting from an initial value X(0)
     (1) X^k = X^k-1(I-AC)+C, k=1,2....
     (2) X^k = X^k-1(2I-AX^k-1)
"""
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
C = np.array([[-0.5,-1.5,1],[-0.5,3.7,-2],[1,-2,1]])
I = [[0 for x in range(3)] for y in range(3)]
for x in range(m):
    I[x][x] = 1
I = np.array(I)

In [67]:
"""
(a) What are sufficient conditions for convergence for these iterations?
    What convergence order do you expect?
    
converges for any initial value X0 iff max|eigen value| < 1
r = spr(I-C^-1A)
convergence order is linear ||x^k+1-x|| <= r ||x^k - x||
"""
def testConvergence():
    matrix = I-(inv(C).dot(A))
    w, v = np.linalg.eig(matrix)
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges") 

testConvergence()

Does not converge


In [62]:
"""
(b) X^0 = I and X^0 = C
"""
def fixedPtIterations(A, C):    
    print("Inverse of A")
    print(inv(A))
    print("\n")


    def iterate(X0, start, end):
        print("Fixed-point iteration: X^k = X^k-1(I-AC)+C")
        X = X0
        k = start
        while (k <= end):
            X = X.dot((I-A.dot(C))) + C
            k += 1
        print(X)
        
        print("Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)")
        X = X0
        k = start
        while (k <= end):
            X = X.dot((2*I)-(A.dot(X)))
            k += 1
        print(X)
    
    #testing with initial value X0 = I
    print("Initial value X0 = I")
    iterate(I, 1, 100)
    print("\n")
    #testing with initial value X0 = C
    print("Initial value X0 = C")
    iterate(C, 1, 100)

In [63]:
fixedPtIterations(A, C)

Inverse of A
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


Initial value X0 = I
Fixed-point iteration: X^k = X^k-1(I-AC)+C
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)
[[ 8843455372529952213 -3452570626832749044 -5898025103523347754]
 [-7384587362514980880 -8963119298963511455  7609586084361821692]
 [ 5004316238054728718  3837384718296084120 -8530989198807102521]]


Initial value X0 = C
Fixed-point iteration: X^k = X^k-1(I-AC)+C
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
