In [60]:
"""
Q1: For which of these matrices (A1, A2) does the jacobi iteration and Gauss-Siedel method converge?
"""
import numpy as np
from scipy.linalg import inv, lu
from math import sqrt, cos, pi

In [8]:
A1 = [[2,-1,2],[1,2,-2],[2,2,2]]
A2 = [[5,5,0],[-1,5,4],[2,3,8]]

In [24]:
"""
Convergence Tests: Every eigenvalue of M=I-P^-1A must have |eigen(M)| < 1
Jacobi Iteration: P = diagonal part D of A
Gauss-Siedel: P = Lower Triangular part of A
"""
def jacobiConvergence(A):
    m, n = len(A), len(A[0])
    
    #constuct Diagonal and Identity matrix
    D = [[0 for x in range(n)] for y in range(m)]
    I = [[0 for x in range(n)] for y in range(m)]
    for x in range(m):
        D[x][x] = A[x][x]
        I[x][x] = 1
        
    #turn into numpy arrays
    A = np.array(A)
    D = np.array(D)
    I = np.array(I)
    
    M = I - (inv(D).dot(A))
    
    w, v = np.linalg.eig(M)
    
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges")

def guasssiedelConvergence(A):
    m, n = len(A), len(A[0])
    
    #construct L and Identity matrix
    P, L, U = lu(A)
    I = [[0 for x in range(n)] for y in range(m)]
    for x in range(m):
        I[x][x] = 1
        
    M = I - (inv(L).dot(A))
    
    w, v = np.linalg.eig(M)
    
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges")

In [25]:
print("Testing Matrix A1")
print("Jacobi Iteration")
jacobiConvergence(A1)
print("Gauss-Siedel")
guasssiedelConvergence(A1)
print("\n")
print("Testing Matrix A2")
print("Jacobi Iteration")
jacobiConvergence(A2)
print("Gauss-Siedel")
guasssiedelConvergence(A2)

Testing Matrix A1
Jacobi Iteration
Does not converge
Gauss-Siedel
Does not converge


Testing Matrix A2
Jacobi Iteration
Converges
Gauss-Siedel
Does not converge


In [65]:
"""
QII: Consider two different fixed-pt iterations to compute the inverse of a regular matrix A(nxn)
     starting from an initial value X(0)
     (1) X^k = X^k-1(I-AC)+C, k=1,2....
     (2) X^k = X^k-1(2I-AX^k-1)
"""
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
C = np.array([[-0.5,-1.5,1],[-0.5,3.7,-2],[1,-2,1]])
I = [[0 for x in range(3)] for y in range(3)]
for x in range(m):
    I[x][x] = 1
I = np.array(I)

In [67]:
"""
(a) What are sufficient conditions for convergence for these iterations?
    What convergence order do you expect?
    
converges for any initial value X0 iff max|eigen value| < 1
r = spr(I-C^-1A)
convergence order is linear ||x^k+1-x|| <= r ||x^k - x||
"""
def testConvergence():
    matrix = I-(inv(C).dot(A))
    w, v = np.linalg.eig(matrix)
    for eigen_val in w: 
        if (abs(eigen_val) >= 1):
            print("Does not converge")
            return
    print("Converges") 

testConvergence()

Does not converge


In [62]:
"""
(b) X^0 = I and X^0 = C
"""
def fixedPtIterations(A, C):    
    print("Inverse of A")
    print(inv(A))
    print("\n")


    def iterate(X0, start, end):
        print("Fixed-point iteration: X^k = X^k-1(I-AC)+C")
        X = X0
        k = start
        while (k <= end):
            X = X.dot((I-A.dot(C))) + C
            k += 1
        print(X)
        
        print("Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)")
        X = X0
        k = start
        while (k <= end):
            X = X.dot((2*I)-(A.dot(X)))
            k += 1
        print(X)
    
    #testing with initial value X0 = I
    print("Initial value X0 = I")
    iterate(I, 1, 100)
    print("\n")
    #testing with initial value X0 = C
    print("Initial value X0 = C")
    iterate(C, 1, 100)

In [63]:
fixedPtIterations(A, C)

Inverse of A
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


Initial value X0 = I
Fixed-point iteration: X^k = X^k-1(I-AC)+C
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)
[[ 8843455372529952213 -3452570626832749044 -5898025103523347754]
 [-7384587362514980880 -8963119298963511455  7609586084361821692]
 [ 5004316238054728718  3837384718296084120 -8530989198807102521]]


Initial value X0 = C
Fixed-point iteration: X^k = X^k-1(I-AC)+C
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
Fixed-point iteration: X^k = X^k-1(2I-AX^k-1)
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [2]:
"""
QIII: Consider the m-dependent matrix A. Solve the system Ax=b with
      (a) Jacobi Method
      (b) Gauss-Siedel Method
      (c) SOR method
      Use m = 2^k, k=1,..,6
      Stopping criterion use ||b-Ax^k||inf <= 10^-8||x^k||inf or k >= 20000
      Use given relaxation parameter for the SOR method
"""
def createMatrixA(m):
    n = m * m 
    A = [[0 for x in range(n)] for y in range(n)]
    i = 0
    while i < n:
        if i + m < n:
            for j in range(1, m):
                A[i+m][i] = -1
                A[i+m+j][i+j] = -1
                A[i][i+m] = -1
                A[i+j][i+m+j] = -1
        for j in range(m):
            A[i+j][i+j] = 4
        for j in range(m-1):
            A[i+j+1][i+j] = -1
            A[i+j][i+j+1] = -1
        i += m
    return A

def createMatrixb(m):
    n = m * m
    b = [[1] for x in range(n)]
    return b

In [91]:
def jacobiMethod(A, b, x=None):
    if x is None:
        x = np.zeros_like(b)
    
    D = np.diag(A)
    R = A - np.diagflat(D)
    
    k = 1
    while ((np.linalg.norm(b-(A.dot(x)), np.inf) > (1e-8)*np.linalg.norm(x, np.inf)) and k < 20000):
        x = (b-np.dot(R,x)) / D
        k += 1
    return k

def gaussSiedel(A, b, x=None):
    [m, n] = np.shape(A)
    
    P, L, U = lu(A)
    x = np.ones((m,1))
    
    k = 1
    while ((np.linalg.norm(b-(A.dot(x)), np.inf) > (1e-8)*np.linalg.norm(x, np.inf)) and k < 20000):
        x_new = np.dot(inv(L), (b-np.dot(U, x)))
        x = x_new
        k += 1
    return k

def sorMethod(A, b, x, omega):
    phi = x[:]
    k = 1
    while ((np.linalg.norm(b-(A.dot(phi)), np.inf) > (1e-8)*np.linalg.norm(phi, np.inf)) and k < 20000):
        for i in range(A.shape[0]):
            sigma = 0
            for j in range(A.shape[1]):
                if j != i:
                    sigma += A[i][j] * phi[j]
            phi[i] = (1 - omega) * phi[i] + (omega / A[i][i]) * (b[i] - sigma)
        k += 1
    return k
    

In [98]:
m_vals = [2**k for k in range(1,7)]
jacobiIterations = []
gaussIterations = []
sorIterations = []
    
for m in m_vals:
    A = np.array(createMatrixA(m))
    b = np.array(createMatrixb(m))
    jacobiIterations.append(jacobiMethod(A, b))
    gaussIterations.append(gaussSiedel(A, b))
    h = 1 / (m + 1)
    sprJ = cos(pi*h)
    omega = 2 / (1 + sqrt(1-(sprJ**2)))
    sorIterations.append(sorMethod(A, b, np.zeros(m*m), omega))

print("m values: {}".format(m_vals))
print("\n" + "Iterations as a funciton of m")
print("Jacobi Method: {}".format(jacobiIterations))
print("Gauss-Siedel Method: {}".format(gaussIterations))
print("SOR Method: {}".format(sorIterations))

    

KeyboardInterrupt: 